### ISSUE TITLE
Where does unpaired captions come from?

### ISSUE THREAD

**Issue by zzy-ucas** [csalt-research/perturb-predict-paraphrase#1]
Hi! It's pleasure to see your paper and code. But I'm confused when I see it  in section 5.5 Paraphrasing Part.

> The paraphraser is trained on the set of unpaired captions UC

 So, the question is: **What is the unpaired captions used in your experiments**? 
As we know that Unlabeled MSCOCO splits only have images without captions. 
Looking forward for your reply! Thanks again!

**Comment by ArjitJ** [comment]
In our low resource settings we only use 1% of the labeled data (images with their paired captions). Captions from the remaining 99% data are used to train the paraphraser model. Since each image can have multiple captions, there are two broad ways of creating training examples for the paraphraser. You could use captions that correspond to the same image, or you could cluster all the captions and use captions from the same cluster to create training examples.
